#!/usr/bin/env node
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

class ReportGenerator {
  constructor(analysisData, postsData) {
    this.analysis = analysisData;
    this.posts = postsData;
  }

  generateMarkdownReport() {
    const { metadata, topics, insights, authors } = this.analysis;
    const date = new Date(metadata.analyzedAt).toLocaleDateString();

    let report = `# LinkedIn Insights Report\n\n`;
    report += `**Generated:** ${date}\n`;
    report += `**Posts Analyzed:** ${metadata.postCount}\n\n`;
    report += `---\n\n`;

    if (topics && topics.themes && topics.themes.length > 0) {
      report += `## 🎯 Top Themes\n\n`;
      topics.themes.forEach((theme, i) => {
        report += `### ${i + 1}. ${theme.name} (${theme.postCount} posts)\n\n`;
        report += `${theme.description}\n\n`;
        if (theme.keyInsights && theme.keyInsights.length > 0) {
          report += `**Key Insights:**\n`;
          theme.keyInsights.forEach(insight => report += `- ${insight}\n`);
          report += `\n`;
        }
      });
    }

    if (insights && insights.keyInsights) {
      report += `## 💡 Most Valuable Insights\n\n`;
      insights.keyInsights.slice(0, 10).forEach((item, i) => {
        const post = this.posts[item.postIndex - 1];
        report += `### ${i + 1}. ${item.insight}\n\n`;
        report += `**Source:** ${item.source}\n`;
        if (post && post.url) {
          report += `**Link:** [View Post](${post.url})\n`;
        }
        report += `\n`;
      });
    }

    if (insights && insights.actionItems && insights.actionItems.length > 0) {
      report += `## ✅ Action Items\n\n`;
      insights.actionItems.forEach(action => report += `- [ ] ${action}\n`);
      report += `\n`;
    }

    if (authors && authors.topAuthors) {
      report += `## 👥 Most Saved Authors\n\n`;
      authors.topAuthors.forEach((author, i) => {
        report += `${i + 1}. ${author.author} (${author.postCount} posts)\n`;
      });
      report += `\n`;
    }

    report += `---\n\n*Generated by LinkedIn Saved Posts Analyzer*\n`;
    return report;
  }

  async save(outputPath = null) {
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = outputPath || path.join(__dirname, `../output/report-${timestamp}.md`);

    const report = this.generateMarkdownReport();
    await fs.writeFile(filename, report);

    console.log(`📝 Report saved to: ${filename}`);
    return filename;
  }
}

function showHelp() {
  console.log(`
📝 LinkedIn Report Generator

USAGE:
  node src/reporter.js [options]

OPTIONS:
  --help, -h          Show this help message
  --output, -o PATH   Specify output markdown file path
  --analysis FILE     Specify analysis JSON file
  --posts FILE        Specify posts JSON file

DESCRIPTION:
  Generates a human-readable markdown report from analysis results.
  Includes:
    • Top themes and topics
    • Key insights with source links
    • Action items checklist
    • Most saved authors

PREREQUISITES:
  1. Extract posts: npm run extract
  2. Analyze posts: npm run analyze
  3. Then generate report: npm run report

EXAMPLES:
  node src/reporter.js
  node src/reporter.js --output my-report.md
  npm run report

OUTPUT FORMAT:
  Markdown file ready to read, share, or commit to documentation.
  Default location: output/report-YYYY-MM-DD.md

NEXT STEPS:
  After generating report:
    • Read the markdown file in your favorite editor
    • Share insights with your team
    • Track action items in your task manager
`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    showHelp();
    process.exit(0);
  }

  console.log('📝 LinkedIn Report Generator\n');

  const outputIndex = args.findIndex(arg => arg === '--output' || arg === '-o');
  const outputPath = outputIndex !== -1 ? args[outputIndex + 1] : null;

  const analysisIndex = args.findIndex(arg => arg === '--analysis');
  const postsIndex = args.findIndex(arg => arg === '--posts');

  const outputDir = path.join(__dirname, '../output');

  let analysisPath, postsPath;

  try {
    if (analysisIndex !== -1 && args[analysisIndex + 1]) {
      analysisPath = path.resolve(args[analysisIndex + 1]);
      await fs.access(analysisPath);
    } else {
      const files = await fs.readdir(outputDir);
      const analysisFiles = files.filter(f => f.startsWith('analysis-'));

      if (analysisFiles.length === 0) {
        console.error('❌ No analysis file found in output/ directory\n');
        console.error('To fix this:');
        console.error('  1. Run: npm run analyze');
        console.error('  2. Or run full pipeline: npm run pipeline\n');
        process.exit(1);
      }

      const latestAnalysis = analysisFiles.sort().reverse()[0];
      analysisPath = path.join(outputDir, latestAnalysis);
      console.log(`📂 Using analysis: ${latestAnalysis}`);
    }

    if (postsIndex !== -1 && args[postsIndex + 1]) {
      postsPath = path.resolve(args[postsIndex + 1]);
      await fs.access(postsPath);
    } else {
      const files = await fs.readdir(outputDir);
      // Exclude sample files and get only real extractions
      const postsFiles = files.filter(f =>
        f.startsWith('saved-posts-') &&
        !f.includes('sample') &&
        f.endsWith('.json')
      );

      if (postsFiles.length === 0) {
        console.error('❌ No posts file found in output/ directory\n');
        console.error('To fix this:');
        console.error('  1. Run: npm run extract');
        console.error('  2. Or run full pipeline: npm run pipeline\n');
        process.exit(1);
      }

      // Sort by date in filename (YYYY-MM-DD format) to get latest
      const latestPosts = postsFiles
        .sort((a, b) => {
          // Extract date from filename: saved-posts-YYYY-MM-DD.json
          const dateA = a.match(/\d{4}-\d{2}-\d{2}/)?.[0] || '';
          const dateB = b.match(/\d{4}-\d{2}-\d{2}/)?.[0] || '';
          return dateB.localeCompare(dateA); // Descending order
        })[0];

      postsPath = path.join(outputDir, latestPosts);
      console.log(`📂 Using posts: ${latestPosts}\n`);
    }
  } catch (error) {
    console.error(`❌ Error reading files: ${error.message}\n`);
    console.error('Make sure you have run the extraction and analysis steps first.');
    console.error('Run with --help for more information.\n');
    process.exit(1);
  }

  console.log('Generating markdown report...\n');

  try {
    const analysisData = JSON.parse(await fs.readFile(analysisPath, 'utf-8'));
    const postsData = JSON.parse(await fs.readFile(postsPath, 'utf-8'));

    const generator = new ReportGenerator(analysisData, postsData);
    const reportPath = await generator.save(outputPath);

    console.log('\n' + '═'.repeat(60));
    console.log('✅ Report Generated Successfully!');
    console.log('═'.repeat(60));
    console.log(`📄 Report saved to: ${reportPath}\n`);
    console.log('Next steps:');
    console.log(`  • Open and read: ${reportPath}`);
    console.log('  • Share insights with your team');
    console.log('  • Track action items from the report\n');
    console.log('Tip: Use a markdown viewer for best reading experience.\n');
  } catch (error) {
    console.error('\n❌ Report generation failed\n');
    console.error(`Error: ${error.message}\n`);
    console.error('Troubleshooting:');
    console.error('  • Check that analysis and posts files are valid JSON');
    console.error('  • Ensure output directory is writable');
    console.error('  • Try running the full pipeline: npm run pipeline\n');
    process.exit(1);
  }
}

export default ReportGenerator;
